%%
%% BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
%% This file has been auto-generated by the confdc compiler.
%% Source: load-dir/check_sync.fxs
%% BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
%% 



-define(vz_check_sync__ns, 1179137305).
-define(vz_check_sync__ns_id, 'http://optimus.verizon.com/check-sync').
-define(vz_check_sync__ns_uri, 'http://optimus.verizon.com/check-sync').
-define(vz_check_sync_services, 284312249).
-define(vz_check_sync_path, 1002915403).
-define(vz_check_sync_outformat, 2033658489).
-define(vz_check_sync_in_sync, 153970244).
-define(vz_check_sync_sync_result, 1939464840).
-define(vz_check_sync_cli, 1771971819).
-define(vz_check_sync_service, 855380710).
-define(vz_check_sync_service_id, 1973115602).
-define(vz_check_sync_name, 1998270519).
-define(vz_check_sync_device, 617911018).
-define(vz_check_sync_check_sync_type, 1658959085).
-define(vz_check_sync_get_services, 472378158).
-define(vz_check_sync_native, 472211213).
-define(vz_check_sync_data, 535242711).
-define(vz_check_sync_error, 126243105).
-define(vz_check_sync_result_xml, 558977045).
-define(vz_check_sync__actionpointid_check_sync, 'check-sync').
-define(vz_check_sync__actionpointid_check_sync_get_services, 'check-sync-get-services').
